[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/hodawang/course_3.0/blob/main/02_ML/part2/Chapter1/Label_Encoder_Example1.ipynb)

In [2]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np
# generate x feature encoder
encX = LabelEncoder()
encX.fit(['看電視', '讀書', '音樂', '游泳'])
# generate y feature encoder
ency = LabelEncoder()
ency.fit(['是', '否'])
# test

LabelEncoder()

In [3]:
# practice
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

encX = LabelEncoder()
# encX.fit(['看電視', '讀書','音樂','游泳'])    #不一定會是根據 List 內的資料順序來序編碼
encX.fit(['看電視', '讀書','音樂','游泳'])
# encX.fit(['WatchTV', 'Reading','Music','Swimming'])
ency= LabelEncoder()
ency.fit(['是','否'])
# print(encX.classes_)
# print(type(encX))

print(encX.classes_)  # '游泳' '看電視' '讀書' '音樂'分別會轉成0,1,2,3
print(ency.classes_)  # 否、是分別會轉成0,1

['游泳' '看電視' '讀書' '音樂']
['否' '是']

In [35]:
print(encX.classes_)  # '游泳' '看電視' '讀書' '音樂'分別會轉成0,1,2,3
print(ency.classes_)  # 否、是分別會轉成0,1

['游泳' '看電視' '讀書' '音樂']
['否' '是']

In [30]:
print(encX.classes_)
print(encY.classes_)

['Music' 'Reading' 'Swimming' 'WatchTV']
['No' 'Yes']

In [9]:
data_Xy = {'興趣':['看電視','讀書','音樂','看電視'], '成功與否':['是','否','是','是']}
df = pd.DataFrame(data_Xy,index=['A1','A2','A3','A4'])
df = df[['興趣', '成功與否']]
df

     興趣 成功與否
A1  看電視    是
A2   讀書    否
A3   音樂    是
A4  看電視    是

In [10]:
data_Xy = {'興趣': ['看電視', '讀書', '音樂', '看電視'], '成功與否': ['是', '否', '否', '是']}
df = pd.DataFrame(data=data_Xy, index=['小明', '小林', '小英', '小陳'])
df = df[['興趣', '成功與否']]
df

     興趣 成功與否
小明  看電視    是
小林   讀書    否
小英   音樂    否
小陳  看電視    是

In [ ]:
from pandas.core.indexes.interval import date_range
df_encode = df.copy()
df_encode['興趣'] = encX.transform(df_encode['興趣']) #將欄位資料替換成數字
df_encode['成功與否'] = ency.transform(df_encode['成功與否'])
df_encode['Leve'] =['H','L','H','H']          #可以加入新的欄位資料
df_encode

In [ ]:
df_encode = df.copy()
df_encode['興趣'] = encX.transform(df_encode['興趣'])
df_encode['成功與否'] = ency.transform(df_encode['成功與否'])

In [16]:
df_encode

    興趣  成功與否 Leve
小明   1     1    H
小林   2     0    L
小英   3     0    H
小陳   1     1    H

In [15]:
prediction = np.array([1,1,0,0])
df['predictio'] = ency.inverse_transform(prediction)    #將數字反轉回去文字表示
df

     興趣 成功與否 predictio
小明  看電視    是         是
小林   讀書    否         是
小英   音樂    否         否
小陳  看電視    是         否

In [ ]:
prediction = np.array([1, 0, 0, 1])
df['prediction'] = ency.inverse_transform(prediction)  # 將預測完的結果做反轉換
df