[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/hodawang/course_3.0/blob/main/02_ML/part2/Chapter1/Label_Encoder_Example2.ipynb)

In [7]:
import pandas as pd
import numpy as np
size_mapping = {'S':2 , 'M':3, 'L':4 ,'XL':5}
label_mapping = {'否':6 , '是':7}

In [1]:
import pandas as pd
import numpy as np
size_mapping = {'S':0, 'M':1, 'L':2, 'XL':3} #define map as dictionary
label_mapping = {'否':0, '是':1} #define map as dictionary

In [2]:
data_Xy = {'衣服size':['XL','S','M','L'],'成功與否':['是','否','否','是']}
df = pd.DataFrame(data = data_Xy, index=['小明','小林','小英','小陳'])
df = df[['衣服size','成功與否']]
df

   衣服size 成功與否
小明     XL    是
小林      S    否
小英      M    否
小陳      L    是

In [8]:
df_encode = df.copy()
df_encode['衣服size'] = df_encode['衣服size'].map(size_mapping)
df_encode['成功與否'] = df_encode['成功與否'].map(label_mapping)

In [9]:
df_encode

    衣服size  成功與否
小明       5     7
小林       2     6
小英       3     6
小陳       4     7