[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/hodawang/course_3.0/blob/main/02_ML/part2/Chapter1/One_Hot_Encoding_Example.ipynb)

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_Xy = {'興趣':['看電視','讀書','音樂','看電視'],'成功與否':['是','否','否','是']}
df = pd.DataFrame(data = data_Xy, index=['小明','小林','小英','小陳'])
df = df[['興趣','成功與否']]
df

     興趣 成功與否
小明  看電視    是
小林   讀書    否
小英   音樂    否
小陳  看電視    是

In [3]:
X = pd.get_dummies(df.iloc[:, 0])  # 針對第一個欄位做get_dummies
X

    看電視  讀書  音樂
小明    1   0   0
小林    0   1   0
小英    0   0   1
小陳    1   0   0

In [4]:
X = pd.get_dummies(df.iloc[:, 1])  # 針對第一個欄位做get_dummies
X

    否  是
小明  0  1
小林  1  0
小英  1  0
小陳  0  1